// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/congratulations/notify": {
            "post": {
                "description": "You must give all fields in structer and then the server can send email by using \"gomail\"",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "This API can notify any person by sending email",
                "parameters": [
                    {
                        "description": "Details about the subscriber and about 'birthday-boy'",
                        "name": "notified",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apptype.Notified"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "The employee was notified",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Something went wrong while we were trying to encrypt data to sends",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "apptype.Notified": {
            "type": "object",
            "properties": {
                "birthday": {
                    "type": "string"
                },
                "birthday_id": {
                    "type": "integer"
                },
                "birthday_name": {
                    "type": "string"
                },
                "birthday_nickname": {
                    "type": "string"
                },
                "subed_email": {
                    "type": "string"
                },
                "subed_id": {
                    "type": "integer"
                },
                "subed_name": {
                    "type": "string"
                },
                "subed_nickname": {
                    "type": "string"
                }
            }
        },
        "rest.Error": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
